[build]
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "PUBLIC_SUPABASE_URL,PUBLIC_SUPABASE_ANON_KEY,SUPABASE_SERVICE_ROLE_KEY"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/functions/**,.netlify/build/**,.netlify/v1/**"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200